const lessons=[
{title:"The Hunger Games — Elizabeth Banks Interview",url:"https://www.youtube.com/watch?v=6NX3eg2hj0M",segment:"00:00–05:00",goal:"Listening + acting vocabulary",vocab:["character","role","audition","opportunity","excited"],expr:["I was really excited about...","I wanted to...","It was an amazing opportunity."],shadow:"I was really excited about the opportunity.",q:"What kind of opportunity would make you really excited?",lines:[["00:14","I was really excited about the opportunity."],["01:02","I wanted to be part of the story."],["02:10","It was an amazing experience for me."]]},
{title:"People Like Us — Elizabeth Banks Interview",url:"https://www.youtube.com/watch?v=AKJTEwKy0YA",segment:"00:00–04:20",goal:"Family + work balance",vocab:["family","parent","balance","responsibility","relationship"],expr:["It's hard to balance...","I try to...","At the same time..."],shadow:"It's hard to balance work and family.",q:"How do you balance work and your personal life?",lines:[["00:20","It's hard to balance work and family."],["01:15","I try to make time for everyone."],["02:24","At the same time, you have to work."]]},
{title:"The Tonight Show — Elizabeth Banks",url:"https://www.youtube.com/watch?v=U9WtsDRW41o",segment:"00:00–05:30",goal:"Informal family English",vocab:["kids","husband","wife","funny","family"],expr:["My kids are...","They always...","It's funny because..."],shadow:"It's funny because they always ask questions.",q:"Tell me something funny that happened recently.",lines:[["00:35","It's funny because they always ask questions."],["01:42","My kids are really curious."],["03:05","They always want to know what happens next."]]},
{title:"Glamour — Step Into My Office",url:"https://www.youtube.com/watch?v=wqfcVjtPY2M",segment:"00:00–06:00",goal:"Career English",vocab:["career","experience","decision","project","ambition"],expr:["I learned about myself...","I wanted to...","I decided to..."],shadow:"I decided to take the opportunity.",q:"What do you really care about in your career?",lines:[["00:26","I learned a lot about myself."],["01:44","I wanted to try something different."],["03:11","I decided to take the opportunity."]]},
{title:"Jimmy Kimmel — Pitch Perfect 3",url:"https://www.youtube.com/watch?v=odrp338hy9I",segment:"00:00–06:00",goal:"Storytelling",vocab:["travel","experience","remember","movie","ended up"],expr:["I got to...","We ended up...","It was really...","I remember..."],shadow:"We ended up staying there for three days.",q:"Tell me about an interesting trip.",lines:[["00:41","I got to travel with the cast."],["02:03","We ended up staying there for three days."],["04:18","I remember it was really funny."]]},
{title:"Boston Accent — Elizabeth Banks",url:"https://www.youtube.com/watch?v=edTFYsmSVjA",segment:"00:00–04:30",goal:"Pronunciation + accent",vocab:["accent","pronunciation","sound","stress","intonation"],expr:["I sound like...","I can't believe...","It reminds me of..."],shadow:"It reminds me of where I grew up.",q:"What pronunciation feature is difficult for you?",lines:[["00:31","It reminds me of where I grew up."],["01:38","I sound completely different."],["03:02","I can't believe how strong the accent is."]]},
{title:"The Miniature Wife — Elizabeth Banks & Matthew Macfadyen",url:"https://www.youtube.com/watch?v=hbSygJe2vVs",segment:"00:00–06:00",goal:"Modern interview English",vocab:["acting","relationship","comedy","interesting","character"],expr:["What I love about...","It's really interesting because...","The idea was..."],shadow:"What I love about the story is the relationship.",q:"What kind of movies or TV shows do you enjoy?",lines:[["00:22","What I love about the story is the relationship."],["02:05","It's really interesting because the characters change."],["04:01","The idea was to make it funny."]]},
{title:"The Kelly Clarkson Show — Elizabeth Banks",url:"https://www.youtube.com/watch?v=Oizk1Y9nYCU",segment:"06:34–09:24 / 12:02–13:42",goal:"Career challenges",vocab:["director","challenge","realize","career","practice"],expr:["I was told that...","I had to figure out...","I realized that..."],shadow:"I realized that I needed more practice.",q:"Tell me about a time when someone underestimated you.",lines:[["06:48","I was told that I needed more practice."],["08:12","I had to figure out what worked."],["12:31","I realized that I needed more practice."]]},
{title:"The Better Sister — Cast Interview",url:"https://www.youtube.com/results?search_query=Elizabeth+Banks+Jessica+Biel+The+Better+Sister+interview",segment:"00:00–07:00",goal:"Story + characters",vocab:["character","complicated","relationship","emotional","story"],expr:["The character is...","What makes it interesting is...","I think the story..."],shadow:"What makes the story interesting is the relationship.",q:"What makes a good story?",lines:[["00:33","The character is complicated."],["02:12","What makes it interesting is the relationship."],["04:37","I think the story is emotional."]]},
{title:"Conan — Elizabeth Banks / Cocaine Bear",url:"https://www.youtube.com/results?search_query=Elizabeth+Banks+Conan+Cocaine+Bear+interview",segment:"11:37–18:00 / 32:00–41:30",goal:"Fast natural conversation",vocab:["humor","story","remember","feel","happen"],expr:["I feel like...","I didn't know...","What happened was...","I remember..."],shadow:"What happened was that we ended up laughing.",q:"Tell me about a surprising experience.",lines:[["11:52","I feel like it was a crazy experience."],["14:05","I didn't know what was going to happen."],["16:28","What happened was that we ended up laughing."]]}
];

const goals=["Getting started","Family & work","Informal English","Career English","Storytelling","Pronunciation","Modern English","Career challenges","Story & characters","Fast conversation"];
const followups=["Can you give me a specific example?","Why was that important to you?","What happened next?","How would you explain that to a friend?","Would you do anything differently?"];

let state=JSON.parse(localStorage.getItem("ee_pwa_v6")||'{"done":[],"xp":0,"answers":{},"scores":{},"errors":[],"current":0}');
let currentDay=1,player=null,videoTimer=null,recognition=null,recorder=null,recordChunks=[],recordBlob=null,deferredInstall=null;

function save(){localStorage.setItem("ee_pwa_v6",JSON.stringify(state));renderHome();}
function nextDay(){for(let d=1;d<=30;d++)if(!state.done.includes(d))return d;return 30;}
function lesson(){return lessons[Math.floor((currentDay-1)/3)%lessons.length]}
function youtubeId(url){const m=url.match(/(?:v=|youtu\.be\/)([A-Za-z0-9_-]{11})/);return m?m[1]:null}
function fmt(s){s=Math.floor(s||0);return String(Math.floor(s/60)).padStart(2,"0")+":"+String(s%60).padStart(2,"0")}
function sec(t){const a=t.split(":").map(Number);return a[0]*60+a[1]}
function toast(t){const e=document.getElementById("toast");e.textContent=t;e.style.display="block";clearTimeout(toast.t);toast.t=setTimeout(()=>e.style.display="none",2200)}
function show(id){document.querySelectorAll(".screen").forEach(x=>x.classList.remove("active"));document.getElementById(id).classList.add("active");if(id==="progress")renderProgress();window.scrollTo(0,0)}
function openLesson(d){currentDay=d;const l=lesson();document.getElementById("lessonDay").textContent="DAY "+d;document.getElementById("lessonTitle").textContent=l.title;document.getElementById("lessonGoal").textContent=l.goal;document.getElementById("segment").textContent=l.segment;document.getElementById("vocab").innerHTML=l.vocab.map(v=>`<span class="chip">${v}</span>`).join("");document.getElementById("expressions").innerHTML=l.expr.map(v=>`<div class="expression">${v}</div>`).join("");document.getElementById("question").textContent=l.q;document.getElementById("answer").value=state.answers[d]||"";document.getElementById("followup").textContent="Answer the coach first.";document.getElementById("feedback").innerHTML="";document.getElementById("review").innerHTML="";document.getElementById("targetText").textContent=l.shadow;document.getElementById("targetTime").textContent="Target sentence";document.getElementById("completeBtn").textContent=state.done.includes(d)?"✓ Lesson completed":"✓ Complete lesson +20 XP";renderTranscript();initPlayer();show("lesson")}
function renderTranscript(){const l=lesson();document.getElementById("transcript").innerHTML=l.lines.map((x,i)=>`<div class="sentence" id="sentence${i}" onclick="selectSentence(${i})"><span class="timestamp">${x[0]}</span><span>${x[1]}</span></div>`).join("")}
function selectSentence(i){const l=lesson(),x=l.lines[i];document.querySelectorAll(".sentence").forEach(e=>e.classList.remove("active"));document.getElementById("sentence"+i).classList.add("active");document.getElementById("targetTime").textContent=x[0];document.getElementById("targetText").textContent=x[1];if(player){player.seekTo(sec(x[0]),true);player.playVideo()}}
function initPlayer(){document.getElementById("youtubePlayer").innerHTML="";if(!window.YT||!window.YT.Player){setTimeout(initPlayer,500);return}const id=youtubeId(lesson().url);if(!id){document.getElementById("videoStatus").textContent="This source is a YouTube search link; open it from the source if no embed is available.";return}player=new YT.Player("youtubePlayer",{videoId:id,width:"100%",height:"100%",playerVars:{playsinline:1,rel:0,modestbranding:1,cc_load_policy:1,cc_lang_pref:"en",origin:location.origin},events:{onReady:()=>{document.getElementById("videoStatus").textContent="Player ready. English captions requested.";startVideoTimer()},onError:()=>document.getElementById("videoStatus").textContent="This video cannot be embedded by its owner. Try another lesson/source."}})}
function onYouTubeIframeAPIReady(){if(document.getElementById("lesson").classList.contains("active"))initPlayer()}
function videoPlay(){player&&player.playVideo()}function videoPause(){player&&player.pauseVideo()}function videoSeek(s){if(player)player.seekTo(Math.max(0,player.getCurrentTime()+s),true)}function videoRate(r){player&&player.setPlaybackRate(r)}
function caption(on){if(!player)return;try{player.setOption("captions","display",on);document.getElementById("videoStatus").textContent="English captions: "+(on?"ON":"OFF")+" when available."}catch(e){toast("Caption control unavailable for this video.")}}
function startVideoTimer(){clearInterval(videoTimer);videoTimer=setInterval(()=>{if(!player||!player.getDuration)return;const t=player.getCurrentTime(),d=player.getDuration();document.getElementById("videoNow").textContent=fmt(t);document.getElementById("videoDur").textContent=fmt(d);document.getElementById("videoRange").value=d?Math.round(t/d*100):0},500)}
function scrub(v){if(player&&player.getDuration())player.seekTo(Number(v)/100*player.getDuration(),true)}
function hearTarget(){const text=document.getElementById("targetText").textContent;if("speechSynthesis"in window){speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang="en-US";u.rate=.88;speechSynthesis.speak(u)}else toast("Text-to-speech is not supported.")}
async function startRecording(){if(!navigator.mediaDevices?.getUserMedia){toast("Microphone is not available in this browser.");return}try{const stream=await navigator.mediaDevices.getUserMedia({audio:true});recordChunks=[];recorder=new MediaRecorder(stream);recorder.ondataavailable=e=>{if(e.data.size)recordChunks.push(e.data)};recorder.onstop=()=>{recordBlob=new Blob(recordChunks,{type:"audio/webm"});document.getElementById("recordedAudio").src=URL.createObjectURL(recordBlob);document.getElementById("recordedAudio").hidden=false;document.getElementById("recordStatus").textContent="Recording saved in this session ✓";stream.getTracks().forEach(t=>t.stop())};recorder.start();document.getElementById("recordStatus").textContent="Recording… imitate the target sentence."}catch(e){toast("Microphone permission was denied.")}}
function stopRecording(){if(recorder&&recorder.state!=="inactive")recorder.stop()}
function playRecording(){const a=document.getElementById("recordedAudio");if(a.hidden){toast("Record something first.");return}a.play()}
function startSpeech(){const R=window.SpeechRecognition||window.webkitSpeechRecognition;if(!R){toast("Speech recognition is not supported here. Type your answer.");return}recognition=new R();recognition.lang="en-US";recognition.continuous=true;recognition.interimResults=true;recognition.onresult=e=>{let text="";for(let i=e.resultIndex;i<e.results.length;i++)text+=e.results[i][0].transcript+" ";document.getElementById("answer").value=(document.getElementById("answer").value+" "+text).trim()};recognition.onerror=e=>toast("Speech recognition: "+e.error);recognition.start();toast("Listening…")}
function stopSpeech(){if(recognition){recognition.stop();recognition=null;toast("Speech capture finished.")}}
function analyzeAnswer(){const text=document.getElementById("answer").value.trim();if(!text){toast("Speak or type an answer first.");return}const words=text.split(/\s+/).filter(Boolean),sentences=text.split(/[.!?]+/).filter(x=>x.trim()).length,unique=new Set(words.map(w=>w.toLowerCase().replace(/[^a-z']/g,""))).size;const flu=Math.min(100,45+Math.min(50,words.length));const grammar=Math.min(100,50+(sentences>=3?20:0)+(words.length>=30?15:0));const vocab=Math.min(100,45+Math.round(unique/Math.max(words.length,1)*50));const total=Math.round((flu+grammar+vocab)/3);state.answers[currentDay]=text;state.scores[currentDay]={flu,grammar,vocab,total,words:words.length,at:Date.now()};let improvement=words.length<25?"Add a specific example and make your answer longer.":sentences<3?"Use at least three complete sentences.":unique/words.length<.55?"Try more varied vocabulary.":"Good structure. Add one concrete detail to sound more natural.";state.errors.push({day:currentDay,text:improvement,at:Date.now()});state.xp+=5;const q=followups[currentDay%followups.length];document.getElementById("feedback").innerHTML=`<div class="feedback"><b>Practice score: ${total}/100</b><div class="scoregrid"><div><b>${flu}</b>Fluency</div><div><b>${grammar}</b>Grammar</div><div><b>${vocab}</b>Vocabulary</div><div><b>${words.length}</b>Words</div></div><p>${improvement}</p></div>`;document.getElementById("followup").textContent=q;save()}
function useFollowup(){const q=document.getElementById("followup").textContent;if(q!=="Answer the coach first.")document.getElementById("question").textContent=q}
function makeReview(){const l=lesson(),items=[["Choose the correct word: I was really ___ about it.",["excited","exciting","excitement"],0],["Choose the natural expression.",[l.expr[0],"I am expression","I expression am"],0],["Use one vocabulary item in a sentence.",["Type your own answer","No answer","Skip"],0]];document.getElementById("review").innerHTML=items.map((q,i)=>`<div class="quizq"><b>${i+1}. ${q[0]}</b><br>${q[1].map((a,j)=>`<button onclick="answerQuiz(this,${j===q[2]})">${a}</button>`).join("")}</div>`).join("")}
function answerQuiz(btn,ok){btn.style.background=ok?"#bbf7d0":"#fecaca";if(ok){state.xp+=5;save();toast("+5 XP")}}
function completeDay(){if(!state.done.includes(currentDay)){state.done.push(currentDay);state.xp+=20;save();toast("Lesson completed +20 XP")}document.getElementById("completeBtn").textContent="✓ Lesson completed"}
function renderHome(){const done=state.done.length,p=Math.round(done/30*100),d=nextDay();document.getElementById("daysDone").textContent=done;document.getElementById("xp").textContent=state.xp;document.getElementById("completion").textContent=p+"%";document.getElementById("progressBar").style.width=p+"%";document.getElementById("road").textContent=done+"/30";document.getElementById("todayTitle").textContent="Day "+d+" — "+goals[(d-1)%goals.length];document.getElementById("todayGoal").textContent=lesson().goal;document.getElementById("streak").textContent=done;document.getElementById("days").innerHTML=Array.from({length:30},(_,i)=>{const n=i+1;return `<button class="day ${state.done.includes(n)?"done":""} ${n===d?"today":""}" onclick="openLesson(${n})">${state.done.includes(n)?"✓ ":""}${n}</button>`}).join("")}
function renderProgress(){const scores=Object.entries(state.scores);document.getElementById("progressBox").innerHTML=`<p><b>${state.done.length}/30</b> lessons completed</p><div class="progress"><i style="width:${state.done.length/30*100}%"></i></div><p><b>${state.xp} XP</b></p>`;const errors=state.errors.slice(-10).reverse();document.getElementById("errors").innerHTML=errors.length?errors.map(e=>`<div class="error"><b>Day ${e.day}</b> — ${e.text}</div>`).join(""):"<p class='muted'>No errors recorded yet.</p>";document.getElementById("history").innerHTML=scores.length?scores.map(([d,s])=>`<div class="expression"><b>Day ${d}</b> — ${s.total}/100 · Fluency ${s.flu} · Grammar ${s.grammar} · Vocabulary ${s.vocab}</div>`).join(""):"<p class='muted'>No speaking attempts yet.</p>"}
function resetProgress(){if(confirm("Reset all local progress?")){localStorage.removeItem("ee_pwa_v6");location.reload()}}
function installPWA(){if(deferredInstall){deferredInstall.prompt();deferredInstall=null}else toast("Use browser menu → Add to Home screen.")}
window.addEventListener("beforeinstallprompt",e=>{e.preventDefault();deferredInstall=e;document.getElementById("installHint").textContent="This app can be installed. Tap Install app."});
window.addEventListener("appinstalled",()=>toast("App installed ✓"));
if("serviceWorker"in navigator)window.addEventListener("load",()=>navigator.serviceWorker.register("sw.js").catch(()=>{}));
renderHome();