const lessons=[
{title:"Screen Test — The New York Times",type:"youtube",url:"https://www.youtube.com/watch?v=NQMtakEDQlw",source:"The New York Times",goal:"Clear interview English",vocab:["career","character","audition","experience","project"],expr:["I remember when...","I was interested in...","What I love about..."],shadow:"I was interested in the character.",q:"What kind of work would you like to do in the future?"},
{title:"The Hunger Games — Elizabeth Banks Interview",type:"youtube",url:"https://www.youtube.com/watch?v=DEFaIp2lbfs",source:"Rotten Tomatoes Coming Soon",goal:"Movie interview English",vocab:["role","character","film","director","audience"],expr:["I think...","It was really fun to...","I wanted to..."],shadow:"I think the character is really interesting.",q:"What movie character would you like to play?"},
{title:"The Hunger Games — Elizabeth Banks Interview (alternate source)",type:"youtube",url:"https://www.youtube.com/watch?v=6NX3eg2hj0M",source:"THG Fansite",goal:"Repeated listening + shadowing",vocab:["story","scene","costume","audience","role"],expr:["For me...","It was important to...","I wanted to make sure..."],shadow:"It was important to understand the character.",q:"What makes a movie memorable for you?"},
{title:"Charlie’s Angels — Elizabeth Banks Q&A",type:"publisher",url:"https://annenberg.usc.edu/news/critical-conversations/qa-elizabeth-banks",source:"USC Annenberg",goal:"Directing + professional English",vocab:["director","inclusion","project","team","inspiration"],expr:["I was inspired by...","I wanted to...","The idea was..."],shadow:"I wanted to create something new.",q:"What inspires you to start a new project?"},
{title:"Elizabeth Banks on the Secret to Great Comedy",type:"publisher",url:"https://www.slate.com/articles/video/conversations_with_slate/2012/04/the_hunger_games_elizabeth_banks_on_judd_apatow_and_the_secret_to_great_comedy_video_.html",source:"Slate",goal:"Comedy + natural speech",vocab:["improv","comedy","influence","actor","performance"],expr:["I love...","What makes it work is...","I was inspired by..."],shadow:"What makes it work is the performance.",q:"What makes a comedy funny for you?"},
{title:"Elizabeth Banks on Parenting and What to Expect",type:"publisher",url:"https://www.slate.com/articles/video/conversations_with_slate/2012/04/elizabeth_banks_on_real_life_parenting_and_what_to_expect_when_you_re_expecting_video_.html",source:"Slate",goal:"Everyday conversational English",vocab:["parenting","experience","family","expect","rewarding"],expr:["In my experience...","It can be...","I think..."],shadow:"In my experience, parenting can be rewarding.",q:"What everyday experience has taught you the most?"},
{title:"Cocaine Bear — Elizabeth Banks Interview",type:"youtube",url:"https://www.youtube.com/watch?v=xN-4mcy1KNQ",source:"ReelBlend",goal:"Long-form listening + filmmaking",vocab:["director","script","stunt","influence","soundtrack"],expr:["What drew me to...","We ended up...","I wanted to..."],shadow:"What drew me to the project was the story.",q:"What kind of story would you like to create?"},
{title:"Elizabeth Banks: ‘always ask for what you want’",type:"publisher",url:"https://abcnews.com/video/122009379/",source:"ABC News / Good Morning America",goal:"Advice + professional English",vocab:["opportunity","confidence","career","role","ask"],expr:["I learned that...","You have to...","I always ask for..."],shadow:"I learned that you have to ask for what you want.",q:"What would you ask for if you were more confident?"},
{title:"Elizabeth Banks and Matthew Macfadyen — The Miniature Wife",type:"publisher",url:"https://abcnews.com/video/132044195/",source:"ABC News",goal:"Current conversational English",vocab:["relationship","challenge","series","balance","experience"],expr:["It was interesting because...","I had to...","We wanted to..."],shadow:"It was interesting because the relationship changes.",q:"What makes a relationship interesting in a story?"},
{title:"3 Ridiculous Questions with Elizabeth Banks",type:"publisher",url:"https://abc.com/video/3fee4d59-cf9f-4929-9b33-314a889f4c9e",source:"Jimmy Kimmel Live! / ABC",goal:"Fast informal English + humor",vocab:["ridiculous","question","answer","funny","comfortable"],expr:["I can't believe...","It turns out...","That's funny because..."],shadow:"It turns out that the answer is more complicated.",q:"What ridiculous question would you ask Elizabeth Banks?"}
];

const goals=["Getting started","Family & work","Informal English","Career English","Storytelling","Pronunciation","Modern English","Career challenges","Story & characters","Fast conversation"];
const followups=["Can you give me a specific example?","Why was that important to you?","What happened next?","How would you explain that to a friend?","Would you do anything differently?"];

let state=JSON.parse(localStorage.getItem("ee_pwa_v6")||'{"done":[],"xp":0,"answers":{},"scores":{},"errors":[],"current":0}');
let currentDay=1,player=null,videoTimer=null,recognition=null,recorder=null,recordChunks=[],recordBlob=null,deferredInstall=null;

function save(){localStorage.setItem("ee_pwa_v6",JSON.stringify(state));renderHome();}
function nextDay(){for(let d=1;d<=30;d++)if(!state.done.includes(d))return d;return 30;}
function lesson(){return lessons[Math.floor((currentDay-1)/3)%lessons.length]}
function youtubeId(url){const m=url.match(/(?:v=|youtu\.be\/)([A-Za-z0-9_-]{11})/);return m?m[1]:null}
function fmt(s){s=Math.floor(s||0);return String(Math.floor(s/60)).padStart(2,"0")+":"+String(s%60).padStart(2,"0")}
function sec(t){const a=t.split(":").map(Number);return a[0]*60+a[1]}
function toast(t){const e=document.getElementById("toast");e.textContent=t;e.style.display="block";clearTimeout(toast.t);toast.t=setTimeout(()=>e.style.display="none",2200)}
function show(id){document.querySelectorAll(".screen").forEach(x=>x.classList.remove("active"));document.getElementById(id).classList.add("active");if(id==="progress")renderProgress();window.scrollTo(0,0)}
function openLesson(d){currentDay=d;const l=lesson();document.getElementById("lessonDay").textContent="DAY "+d;document.getElementById("lessonTitle").textContent=l.title;document.getElementById("lessonGoal").textContent=l.goal;document.getElementById("segment").textContent=l.segment;document.getElementById("vocab").innerHTML=l.vocab.map(v=>`<span class="chip">${v}</span>`).join("");document.getElementById("expressions").innerHTML=l.expr.map(v=>`<div class="expression">${v}</div>`).join("");document.getElementById("question").textContent=l.q;document.getElementById("answer").value=state.answers[d]||"";document.getElementById("followup").textContent="Answer the coach first.";document.getElementById("feedback").innerHTML="";document.getElementById("review").innerHTML="";document.getElementById("targetText").textContent=l.shadow;document.getElementById("targetTime").textContent="Target sentence";document.getElementById("completeBtn").textContent=state.done.includes(d)?"✓ Lesson completed":"✓ Complete lesson +20 XP";renderTranscript();initPlayer();show("lesson")}
function renderTranscript(){const l=lesson();document.getElementById("transcript").innerHTML=l.lines.map((x,i)=>`<div class="sentence" id="sentence${i}" onclick="selectSentence(${i})"><span class="timestamp">${x[0]}</span><span>${x[1]}</span></div>`).join("")}
function selectSentence(i){const l=lesson(),x=l.lines[i];document.querySelectorAll(".sentence").forEach(e=>e.classList.remove("active"));document.getElementById("sentence"+i).classList.add("active");document.getElementById("targetTime").textContent=x[0];document.getElementById("targetText").textContent=x[1];if(player){player.seekTo(sec(x[0]),true);player.playVideo()}}
function initPlayer(){
 const box=document.getElementById("youtubePlayer"); box.innerHTML=""; const l=lesson();
 const status=document.getElementById("videoStatus");
 if(l.type==="youtube"){
   if(!window.YT||!window.YT.Player){setTimeout(initPlayer,500);return}
   const id=youtubeId(l.url);
   player=new YT.Player("youtubePlayer",{videoId:id,width:"100%",height:"100%",host:"https://www.youtube-nocookie.com",playerVars:{playsinline:1,rel:0,modestbranding:1,cc_load_policy:1,cc_lang_pref:"en",origin:location.origin,enablejsapi:1},events:{onReady:()=>{status.innerHTML='YouTube embedded player ready. <span class="badge">Hybrid A</span>';startVideoTimer()},onError:(e)=>{showFallback(l,"YouTube requires verification or blocks embedded playback (error "+e.data+").")}}});
 } else {
   box.innerHTML=`<iframe class="publisherFrame" src="${l.url}" title="${l.title}" loading="lazy" referrerpolicy="strict-origin-when-cross-origin" allow="autoplay; fullscreen" ></iframe><div class="frameFallback"><a href="${l.url}" target="_blank" rel="noopener">Open official source</a></div>`;
   status.innerHTML=`Trying the official publisher page inside the app. <span class="badge">Hybrid B</span>`;
 }
}
function showFallback(l,msg){const box=document.getElementById("youtubePlayer");box.innerHTML=`<div class="fallbackCard"><div class="fallbackIcon">↗</div><h3>Embedded playback is unavailable</h3><p>${msg}</p><a class="primary linkbtn" href="${l.url}" target="_blank" rel="noopener">Open official video/source</a><small>This does not bypass YouTube verification; it simply gives you the publisher/YouTube page.</small></div>`;document.getElementById("videoStatus").innerHTML='Hybrid fallback activated.'}

function onYouTubeIframeAPIReady(){if(document.getElementById("lesson").classList.contains("active"))initPlayer()}
function videoPlay(){player&&player.playVideo()}function videoPause(){player&&player.pauseVideo()}function videoSeek(s){if(player)player.seekTo(Math.max(0,player.getCurrentTime()+s),true)}function videoRate(r){player&&player.setPlaybackRate(r)}
function caption(on){if(!player)return;try{player.setOption("captions","display",on);document.getElementById("videoStatus").textContent="English captions: "+(on?"ON":"OFF")+" when available."}catch(e){toast("Caption control unavailable for this video.")}}
function startVideoTimer(){clearInterval(videoTimer);videoTimer=setInterval(()=>{if(!player||!player.getDuration)return;const t=player.getCurrentTime(),d=player.getDuration();document.getElementById("videoNow").textContent=fmt(t);document.getElementById("videoDur").textContent=fmt(d);document.getElementById("videoRange").value=d?Math.round(t/d*100):0},500)}
function scrub(v){if(player&&player.getDuration())player.seekTo(Number(v)/100*player.getDuration(),true)}
function hearTarget(){const text=document.getElementById("targetText").textContent;if("speechSynthesis"in window){speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang="en-US";u.rate=.88;speechSynthesis.speak(u)}else toast("Text-to-speech is not supported.")}
async function startRecording(){if(!navigator.mediaDevices?.getUserMedia){toast("Microphone is not available in this browser.");return}try{const stream=await navigator.mediaDevices.getUserMedia({audio:true});recordChunks=[];recorder=new MediaRecorder(stream);recorder.ondataavailable=e=>{if(e.data.size)recordChunks.push(e.data)};recorder.onstop=()=>{recordBlob=new Blob(recordChunks,{type:"audio/webm"});document.getElementById("recordedAudio").src=URL.createObjectURL(recordBlob);document.getElementById("recordedAudio").hidden=false;document.getElementById("recordStatus").textContent="Recording saved in this session ✓";stream.getTracks().forEach(t=>t.stop())};recorder.start();document.getElementById("recordStatus").textContent="Recording… imitate the target sentence."}catch(e){toast("Microphone permission was denied.")}}
function stopRecording(){if(recorder&&recorder.state!=="inactive")recorder.stop()}
function playRecording(){const a=document.getElementById("recordedAudio");if(a.hidden){toast("Record something first.");return}a.play()}
function startSpeech(){const R=window.SpeechRecognition||window.webkitSpeechRecognition;if(!R){toast("Speech recognition is not supported here. Type your answer.");return}recognition=new R();recognition.lang="en-US";recognition.continuous=true;recognition.interimResults=true;recognition.onresult=e=>{let text="";for(let i=e.resultIndex;i<e.results.length;i++)text+=e.results[i][0].transcript+" ";document.getElementById("answer").value=(document.getElementById("answer").value+" "+text).trim()};recognition.onerror=e=>toast("Speech recognition: "+e.error);recognition.start();toast("Listening…")}
function stopSpeech(){if(recognition){recognition.stop();recognition=null;toast("Speech capture finished.")}}
function analyzeAnswer(){const text=document.getElementById("answer").value.trim();if(!text){toast("Speak or type an answer first.");return}const words=text.split(/\s+/).filter(Boolean),sentences=text.split(/[.!?]+/).filter(x=>x.trim()).length,unique=new Set(words.map(w=>w.toLowerCase().replace(/[^a-z']/g,""))).size;const flu=Math.min(100,45+Math.min(50,words.length));const grammar=Math.min(100,50+(sentences>=3?20:0)+(words.length>=30?15:0));const vocab=Math.min(100,45+Math.round(unique/Math.max(words.length,1)*50));const total=Math.round((flu+grammar+vocab)/3);state.answers[currentDay]=text;state.scores[currentDay]={flu,grammar,vocab,total,words:words.length,at:Date.now()};let improvement=words.length<25?"Add a specific example and make your answer longer.":sentences<3?"Use at least three complete sentences.":unique/words.length<.55?"Try more varied vocabulary.":"Good structure. Add one concrete detail to sound more natural.";state.errors.push({day:currentDay,text:improvement,at:Date.now()});state.xp+=5;const q=followups[currentDay%followups.length];document.getElementById("feedback").innerHTML=`<div class="feedback"><b>Practice score: ${total}/100</b><div class="scoregrid"><div><b>${flu}</b>Fluency</div><div><b>${grammar}</b>Grammar</div><div><b>${vocab}</b>Vocabulary</div><div><b>${words.length}</b>Words</div></div><p>${improvement}</p></div>`;document.getElementById("followup").textContent=q;save()}
function useFollowup(){const q=document.getElementById("followup").textContent;if(q!=="Answer the coach first.")document.getElementById("question").textContent=q}
function makeReview(){const l=lesson(),items=[["Choose the correct word: I was really ___ about it.",["excited","exciting","excitement"],0],["Choose the natural expression.",[l.expr[0],"I am expression","I expression am"],0],["Use one vocabulary item in a sentence.",["Type your own answer","No answer","Skip"],0]];document.getElementById("review").innerHTML=items.map((q,i)=>`<div class="quizq"><b>${i+1}. ${q[0]}</b><br>${q[1].map((a,j)=>`<button onclick="answerQuiz(this,${j===q[2]})">${a}</button>`).join("")}</div>`).join("")}
function answerQuiz(btn,ok){btn.style.background=ok?"#bbf7d0":"#fecaca";if(ok){state.xp+=5;save();toast("+5 XP")}}
function completeDay(){if(!state.done.includes(currentDay)){state.done.push(currentDay);state.xp+=20;save();toast("Lesson completed +20 XP")}document.getElementById("completeBtn").textContent="✓ Lesson completed"}
function renderHome(){const done=state.done.length,p=Math.round(done/30*100),d=nextDay();document.getElementById("daysDone").textContent=done;document.getElementById("xp").textContent=state.xp;document.getElementById("completion").textContent=p+"%";document.getElementById("progressBar").style.width=p+"%";document.getElementById("road").textContent=done+"/30";document.getElementById("todayTitle").textContent="Day "+d+" — "+goals[(d-1)%goals.length];document.getElementById("todayGoal").textContent=lesson().goal;document.getElementById("streak").textContent=done;document.getElementById("days").innerHTML=Array.from({length:30},(_,i)=>{const n=i+1;return `<button class="day ${state.done.includes(n)?"done":""} ${n===d?"today":""}" onclick="openLesson(${n})">${state.done.includes(n)?"✓ ":""}${n}</button>`}).join("")}
function renderProgress(){const scores=Object.entries(state.scores);document.getElementById("progressBox").innerHTML=`<p><b>${state.done.length}/30</b> lessons completed</p><div class="progress"><i style="width:${state.done.length/30*100}%"></i></div><p><b>${state.xp} XP</b></p>`;const errors=state.errors.slice(-10).reverse();document.getElementById("errors").innerHTML=errors.length?errors.map(e=>`<div class="error"><b>Day ${e.day}</b> — ${e.text}</div>`).join(""):"<p class='muted'>No errors recorded yet.</p>";document.getElementById("history").innerHTML=scores.length?scores.map(([d,s])=>`<div class="expression"><b>Day ${d}</b> — ${s.total}/100 · Fluency ${s.flu} · Grammar ${s.grammar} · Vocabulary ${s.vocab}</div>`).join(""):"<p class='muted'>No speaking attempts yet.</p>"}
function resetProgress(){if(confirm("Reset all local progress?")){localStorage.removeItem("ee_pwa_v6");location.reload()}}
function installPWA(){if(deferredInstall){deferredInstall.prompt();deferredInstall=null}else toast("Use browser menu → Add to Home screen.")}
window.addEventListener("beforeinstallprompt",e=>{e.preventDefault();deferredInstall=e;document.getElementById("installHint").textContent="This app can be installed. Tap Install app."});
window.addEventListener("appinstalled",()=>toast("App installed ✓"));
if("serviceWorker"in navigator)window.addEventListener("load",()=>navigator.serviceWorker.register("sw.js").catch(()=>{}));
renderHome();