const lessons=[
{title:"Screen Test — The New York Times (2008)",url:"https://www.youtube.com/watch?v=NQMtakEDQlw",source:"The New York Times",goal:"Long-form listening + interview English",vocab:["career","character","audition","experience","project"],expr:["I remember when...","What I love about...","I was interested in..."],shadow:"I was interested in the character.",q:"What kind of work would you like to do in the future?",lines:[["00:00","Elizabeth Banks discusses her career and acting."],["00:45","I was interested in the character."],["01:50","I remember when I first started acting."]]},
{title:"The Hunger Games — Elizabeth Banks Interview (2012)",url:"https://www.youtube.com/watch?v=DEFaIp2lbfs",source:"Rotten Tomatoes Coming Soon",goal:"Movie interview + clear American English",vocab:["role","character","book","film","director"],expr:["I think the character...","It was really fun to...","I wanted to..."],shadow:"I think the character is really interesting.",q:"What movie character would you like to play?",lines:[["00:00","Elizabeth Banks talks about The Hunger Games."],["00:45","I think the character is really interesting."],["01:40","It was really fun to work on the film."]]},
{title:"The Hunger Games — Elizabeth Banks Interview (2012)",url:"https://www.youtube.com/watch?v=6NX3eg2hj0M",source:"THG Fansite",goal:"Repeated listening + shadowing",vocab:["audience","story","role","scene","costume"],expr:["I wanted to make sure...","For me...","It was important to..."],shadow:"It was important to understand the character.",q:"What makes a movie memorable for you?",lines:[["00:00","Elizabeth Banks discusses The Hunger Games."],["00:50","It was important to understand the character."],["02:00","For me, the story was really important."]]},
{title:"The Tonight Show — Elizabeth Banks' Sons",url:"https://www.youtube.com/watch?v=U9WtsDRW41o",source:"The Tonight Show Starring Jimmy Fallon",goal:"Natural conversation + parenting vocabulary",vocab:["kids","sons","family","raise","funny"],expr:["My kids...","They always...","It's funny because..."],shadow:"It's funny because they always ask questions.",q:"Tell me something funny about your family.",lines:[["00:00","Elizabeth Banks talks about raising her two boys."],["00:55","My kids are really funny."],["01:55","They always want to know what happens next."]]},
{title:"The Tonight Show — Hot Cocoa & LEGO Movie 2",url:"https://www.youtube.com/watch?v=yHCKZvrKWHE",source:"The Tonight Show Starring Jimmy Fallon",goal:"Fast informal English + storytelling",vocab:["skiing","scam","voice","character","recording"],expr:["I figured out...","We ended up...","I got to..."],shadow:"We ended up having a great time.",q:"Tell me about a funny thing that happened on a trip.",lines:[["00:00","Elizabeth Banks chats with Jimmy about skiing."],["00:55","I figured out how to get free hot chocolate."],["02:00","I got to play different characters."]]},
{title:"Charlie’s Angels — GMA",url:"https://www.youtube.com/watch?v=AGYsz5jEQo0",source:"Good Morning America",goal:"Career + directing English",vocab:["director","inspiration","film","team","project"],expr:["I was inspired by...","I wanted to...","The idea was..."],shadow:"I was inspired by the original series.",q:"What inspires you to start a new project?",lines:[["00:00","Elizabeth Banks discusses the new Charlie's Angels."],["00:55","I was inspired by the original series."],["02:05","I wanted to create something new."]]},
{title:"Cocaine Bear — ReelBlend Interview",url:"https://www.youtube.com/watch?v=xN-4mcy1KNQ",source:"ReelBlend Podcast",goal:"Longer listening + filmmaking vocabulary",vocab:["director","stunt","influence","script","comedy"],expr:["What drew me to...","I wanted to explore...","We ended up..."],shadow:"What drew me to the project was the story.",q:"What kind of story would you like to create?",lines:[["13:51","Elizabeth Banks joins ReelBlend for an interview."],["14:30","What drew me to the project was the story."],["18:00","We ended up creating something very unusual."]]},
{title:"The Kelly Clarkson Show — Elizabeth Banks (2026)",url:"https://www.youtube.com/watch?v=Oizk1Y9nYCU",source:"The Kelly Clarkson Show",goal:"Current conversational English + career",vocab:["career","director","challenge","props","experience"],expr:["I realized that...","I had to...","It was interesting because..."],shadow:"I realized that I had to keep going.",q:"Tell me about a challenge that made you stronger.",lines:[["06:34","Elizabeth Banks discusses The Miniature Wife."],["08:12","I had to figure out what worked."],["12:07","I realized that I had to keep going."]]},
{title:"Jimmy Kimmel Live — Miniature Wife (2026)",url:"https://abc.com/video/7763bbfc-d012-4243-875f-72583169a4e5/playlist/PL5523099034",source:"ABC / Jimmy Kimmel Live",external:true,goal:"Natural conversation + humor",vocab:["props","children","spring break","comfortable","experience"],expr:["I can't believe...","We decided to...","It turns out..."],shadow:"We decided to make it really funny.",q:"How do you explain something difficult to a child?",lines:[["00:00","Elizabeth Banks talks about The Miniature Wife."],["03:00","We decided to make it really funny."],["07:00","It turns out that the props were huge."]]},
{title:"Good Morning America — Always Ask for What You Want (2025)",url:"https://abcnews.com/video/122009379/",source:"ABC News / Good Morning America",external:true,goal:"Advice + professional English",vocab:["opportunity","ask","career","role","confidence"],expr:["I always ask for...","You have to...","I learned that..."],shadow:"I learned that you have to ask for what you want.",q:"What would you ask for if you were more confident?",lines:[["00:00","Elizabeth Banks discusses her newest role and career."],["00:40","I learned that you have to ask for what you want."],["01:30","You have to be confident about your work."]]}
];

const goals=["Getting started","Family & work","Informal English","Career English","Storytelling","Pronunciation","Modern English","Career challenges","Story & characters","Fast conversation"];
const followups=["Can you give me a specific example?","Why was that important to you?","What happened next?","How would you explain that to a friend?","Would you do anything differently?"];

let state=JSON.parse(localStorage.getItem("ee_pwa_v6")||'{"done":[],"xp":0,"answers":{},"scores":{},"errors":[],"current":0}');
let currentDay=1,player=null,videoTimer=null,recognition=null,recorder=null,recordChunks=[],recordBlob=null,deferredInstall=null;

function save(){localStorage.setItem("ee_pwa_v6",JSON.stringify(state));renderHome();}
function nextDay(){for(let d=1;d<=30;d++)if(!state.done.includes(d))return d;return 30;}
function lesson(){return lessons[Math.floor((currentDay-1)/3)%lessons.length]}
function youtubeId(url){const m=url.match(/(?:v=|youtu\.be\/)([A-Za-z0-9_-]{11})/);return m?m[1]:null}
function fmt(s){s=Math.floor(s||0);return String(Math.floor(s/60)).padStart(2,"0")+":"+String(s%60).padStart(2,"0")}
function sec(t){const a=t.split(":").map(Number);return a[0]*60+a[1]}
function toast(t){const e=document.getElementById("toast");e.textContent=t;e.style.display="block";clearTimeout(toast.t);toast.t=setTimeout(()=>e.style.display="none",2200)}
function show(id){document.querySelectorAll(".screen").forEach(x=>x.classList.remove("active"));document.getElementById(id).classList.add("active");if(id==="progress")renderProgress();window.scrollTo(0,0)}
function openLesson(d){currentDay=d;const l=lesson();document.getElementById("lessonDay").textContent="DAY "+d;document.getElementById("lessonTitle").textContent=l.title;document.getElementById("lessonGoal").textContent=l.goal;document.getElementById("segment").textContent=l.segment;document.getElementById("vocab").innerHTML=l.vocab.map(v=>`<span class="chip">${v}</span>`).join("");document.getElementById("expressions").innerHTML=l.expr.map(v=>`<div class="expression">${v}</div>`).join("");document.getElementById("question").textContent=l.q;document.getElementById("answer").value=state.answers[d]||"";document.getElementById("followup").textContent="Answer the coach first.";document.getElementById("feedback").innerHTML="";document.getElementById("review").innerHTML="";document.getElementById("targetText").textContent=l.shadow;document.getElementById("targetTime").textContent="Target sentence";document.getElementById("completeBtn").textContent=state.done.includes(d)?"✓ Lesson completed":"✓ Complete lesson +20 XP";renderTranscript();initPlayer();show("lesson")}
function renderTranscript(){const l=lesson();document.getElementById("transcript").innerHTML=l.lines.map((x,i)=>`<div class="sentence" id="sentence${i}" onclick="selectSentence(${i})"><span class="timestamp">${x[0]}</span><span>${x[1]}</span></div>`).join("")}
function selectSentence(i){const l=lesson(),x=l.lines[i];document.querySelectorAll(".sentence").forEach(e=>e.classList.remove("active"));document.getElementById("sentence"+i).classList.add("active");document.getElementById("targetTime").textContent=x[0];document.getElementById("targetText").textContent=x[1];if(player){player.seekTo(sec(x[0]),true);player.playVideo()}}
function initPlayer(){
 const box=document.getElementById("youtubePlayer"); box.innerHTML="";
 const l=lesson();
 if(l.external || !youtubeId(l.url)){
  box.innerHTML=`<div class="externalVideo"><div><b>Official external video source</b><p>${l.source}</p><a class="primary linkbtn" href="${l.url}" target="_blank" rel="noopener">Open video</a></div></div>`;
  document.getElementById("videoStatus").textContent="Official broadcaster source; playback opens externally.";
  return;
 }
 if(!window.YT||!window.YT.Player){setTimeout(initPlayer,500);return}
 const id=youtubeId(l.url);
 player=new YT.Player("youtubePlayer",{videoId:id,width:"100%",height:"100%",host:"https://www.youtube-nocookie.com",
 playerVars:{playsinline:1,rel:0,modestbranding:1,cc_load_policy:1,cc_lang_pref:"en",origin:location.origin,enablejsapi:1},
 events:{onReady:()=>{document.getElementById("videoStatus").textContent="YouTube player ready. English captions requested when available.";startVideoTimer()},
 onError:(e)=>{document.getElementById("videoStatus").innerHTML=`Embedded playback unavailable (YouTube error ${e.data}). <a href="${l.url}" target="_blank" rel="noopener">Open on YouTube</a>`;}}});
}
function onYouTubeIframeAPIReady(){if(document.getElementById("lesson").classList.contains("active"))initPlayer()}
function videoPlay(){player&&player.playVideo()}function videoPause(){player&&player.pauseVideo()}function videoSeek(s){if(player)player.seekTo(Math.max(0,player.getCurrentTime()+s),true)}function videoRate(r){player&&player.setPlaybackRate(r)}
function caption(on){if(!player)return;try{player.setOption("captions","display",on);document.getElementById("videoStatus").textContent="English captions: "+(on?"ON":"OFF")+" when available."}catch(e){toast("Caption control unavailable for this video.")}}
function startVideoTimer(){clearInterval(videoTimer);videoTimer=setInterval(()=>{if(!player||!player.getDuration)return;const t=player.getCurrentTime(),d=player.getDuration();document.getElementById("videoNow").textContent=fmt(t);document.getElementById("videoDur").textContent=fmt(d);document.getElementById("videoRange").value=d?Math.round(t/d*100):0},500)}
function scrub(v){if(player&&player.getDuration())player.seekTo(Number(v)/100*player.getDuration(),true)}
function hearTarget(){const text=document.getElementById("targetText").textContent;if("speechSynthesis"in window){speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang="en-US";u.rate=.88;speechSynthesis.speak(u)}else toast("Text-to-speech is not supported.")}
async function startRecording(){if(!navigator.mediaDevices?.getUserMedia){toast("Microphone is not available in this browser.");return}try{const stream=await navigator.mediaDevices.getUserMedia({audio:true});recordChunks=[];recorder=new MediaRecorder(stream);recorder.ondataavailable=e=>{if(e.data.size)recordChunks.push(e.data)};recorder.onstop=()=>{recordBlob=new Blob(recordChunks,{type:"audio/webm"});document.getElementById("recordedAudio").src=URL.createObjectURL(recordBlob);document.getElementById("recordedAudio").hidden=false;document.getElementById("recordStatus").textContent="Recording saved in this session ✓";stream.getTracks().forEach(t=>t.stop())};recorder.start();document.getElementById("recordStatus").textContent="Recording… imitate the target sentence."}catch(e){toast("Microphone permission was denied.")}}
function stopRecording(){if(recorder&&recorder.state!=="inactive")recorder.stop()}
function playRecording(){const a=document.getElementById("recordedAudio");if(a.hidden){toast("Record something first.");return}a.play()}
function startSpeech(){const R=window.SpeechRecognition||window.webkitSpeechRecognition;if(!R){toast("Speech recognition is not supported here. Type your answer.");return}recognition=new R();recognition.lang="en-US";recognition.continuous=true;recognition.interimResults=true;recognition.onresult=e=>{let text="";for(let i=e.resultIndex;i<e.results.length;i++)text+=e.results[i][0].transcript+" ";document.getElementById("answer").value=(document.getElementById("answer").value+" "+text).trim()};recognition.onerror=e=>toast("Speech recognition: "+e.error);recognition.start();toast("Listening…")}
function stopSpeech(){if(recognition){recognition.stop();recognition=null;toast("Speech capture finished.")}}
function analyzeAnswer(){const text=document.getElementById("answer").value.trim();if(!text){toast("Speak or type an answer first.");return}const words=text.split(/\s+/).filter(Boolean),sentences=text.split(/[.!?]+/).filter(x=>x.trim()).length,unique=new Set(words.map(w=>w.toLowerCase().replace(/[^a-z']/g,""))).size;const flu=Math.min(100,45+Math.min(50,words.length));const grammar=Math.min(100,50+(sentences>=3?20:0)+(words.length>=30?15:0));const vocab=Math.min(100,45+Math.round(unique/Math.max(words.length,1)*50));const total=Math.round((flu+grammar+vocab)/3);state.answers[currentDay]=text;state.scores[currentDay]={flu,grammar,vocab,total,words:words.length,at:Date.now()};let improvement=words.length<25?"Add a specific example and make your answer longer.":sentences<3?"Use at least three complete sentences.":unique/words.length<.55?"Try more varied vocabulary.":"Good structure. Add one concrete detail to sound more natural.";state.errors.push({day:currentDay,text:improvement,at:Date.now()});state.xp+=5;const q=followups[currentDay%followups.length];document.getElementById("feedback").innerHTML=`<div class="feedback"><b>Practice score: ${total}/100</b><div class="scoregrid"><div><b>${flu}</b>Fluency</div><div><b>${grammar}</b>Grammar</div><div><b>${vocab}</b>Vocabulary</div><div><b>${words.length}</b>Words</div></div><p>${improvement}</p></div>`;document.getElementById("followup").textContent=q;save()}
function useFollowup(){const q=document.getElementById("followup").textContent;if(q!=="Answer the coach first.")document.getElementById("question").textContent=q}
function makeReview(){const l=lesson(),items=[["Choose the correct word: I was really ___ about it.",["excited","exciting","excitement"],0],["Choose the natural expression.",[l.expr[0],"I am expression","I expression am"],0],["Use one vocabulary item in a sentence.",["Type your own answer","No answer","Skip"],0]];document.getElementById("review").innerHTML=items.map((q,i)=>`<div class="quizq"><b>${i+1}. ${q[0]}</b><br>${q[1].map((a,j)=>`<button onclick="answerQuiz(this,${j===q[2]})">${a}</button>`).join("")}</div>`).join("")}
function answerQuiz(btn,ok){btn.style.background=ok?"#bbf7d0":"#fecaca";if(ok){state.xp+=5;save();toast("+5 XP")}}
function completeDay(){if(!state.done.includes(currentDay)){state.done.push(currentDay);state.xp+=20;save();toast("Lesson completed +20 XP")}document.getElementById("completeBtn").textContent="✓ Lesson completed"}
function renderHome(){const done=state.done.length,p=Math.round(done/30*100),d=nextDay();document.getElementById("daysDone").textContent=done;document.getElementById("xp").textContent=state.xp;document.getElementById("completion").textContent=p+"%";document.getElementById("progressBar").style.width=p+"%";document.getElementById("road").textContent=done+"/30";document.getElementById("todayTitle").textContent="Day "+d+" — "+goals[(d-1)%goals.length];document.getElementById("todayGoal").textContent=lesson().goal;document.getElementById("streak").textContent=done;document.getElementById("days").innerHTML=Array.from({length:30},(_,i)=>{const n=i+1;return `<button class="day ${state.done.includes(n)?"done":""} ${n===d?"today":""}" onclick="openLesson(${n})">${state.done.includes(n)?"✓ ":""}${n}</button>`}).join("")}
function renderProgress(){const scores=Object.entries(state.scores);document.getElementById("progressBox").innerHTML=`<p><b>${state.done.length}/30</b> lessons completed</p><div class="progress"><i style="width:${state.done.length/30*100}%"></i></div><p><b>${state.xp} XP</b></p>`;const errors=state.errors.slice(-10).reverse();document.getElementById("errors").innerHTML=errors.length?errors.map(e=>`<div class="error"><b>Day ${e.day}</b> — ${e.text}</div>`).join(""):"<p class='muted'>No errors recorded yet.</p>";document.getElementById("history").innerHTML=scores.length?scores.map(([d,s])=>`<div class="expression"><b>Day ${d}</b> — ${s.total}/100 · Fluency ${s.flu} · Grammar ${s.grammar} · Vocabulary ${s.vocab}</div>`).join(""):"<p class='muted'>No speaking attempts yet.</p>"}
function resetProgress(){if(confirm("Reset all local progress?")){localStorage.removeItem("ee_pwa_v6");location.reload()}}
function installPWA(){if(deferredInstall){deferredInstall.prompt();deferredInstall=null}else toast("Use browser menu → Add to Home screen.")}
window.addEventListener("beforeinstallprompt",e=>{e.preventDefault();deferredInstall=e;document.getElementById("installHint").textContent="This app can be installed. Tap Install app."});
window.addEventListener("appinstalled",()=>toast("App installed ✓"));
if("serviceWorker"in navigator)window.addEventListener("load",()=>navigator.serviceWorker.register("sw.js").catch(()=>{}));
renderHome();